const baseURL="http://127.0.0.1:8089"
export const checkToken=baseURL+"/checkUserToken"
export const login=baseURL+"/user/login"
export const logout=baseURL+"/user/logout"
export const register=baseURL+"/user/register"
export const getInfo=baseURL+"/user/getMyInfo"
export const updateInfo=baseURL+"/user/updateInfo"
export const updatePwd=baseURL+"/user/updatePwd"
export const getSubjects=baseURL+"/getSubjects"
export const getKinds=baseURL+"/getKinds"
export const search=baseURL+"/search"
export const getCollection=baseURL+"/user/getCollections"
export const collectCase=baseURL+"/user/collectCase"
export const cancleCollect=baseURL+"/user/cancleCollect"
export const getCase=baseURL+"/getCase"
export const getPointfile=baseURL+"/user/getPointfile"
export const getNotices=baseURL+"/getNotices"
export const getNotice=baseURL+"/getNotice"
export const getMycollection=baseURL+"/user/mycollection"
export const getMycase=baseURL+"/user/getMycase"
export const getKey = baseURL+"/getKey"
export const uploadImg= baseURL + "/upload/uploadImg"
export const uploadVideo = baseURL + "/upload/uploadVideo"
export const uploadFile= baseURL + "/upload/uploadFile"
export const uploadPointfile=baseURL+"/upload/uploadPointfile"
//用于删除未提交的案例的积分文件
export const delPointfile=baseURL+"/upload/delFile"
//用于删除已经存在的案例的积分文件
export const delEditfile=baseURL+"/upload/delEditfile"
export const addCase=baseURL+"/case/addCase"
export const updatePFname=baseURL+"/upload/editpfname"
export const editCase=baseURL+"/editCase"
export const delCase=baseURL+"/user/delMycase"
export const searchCasebypage=baseURL+"/searchByPage"
export const searchCasenum=baseURL+"/searchCasenum"

